name: Trello CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Gihub Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: Node 설치
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'

      - name: 의존성(라이브러리) 설치
        run: npm ci

      - name: .env파일 만들기
        run: |
          echo '${{ secrets.ENV }}' > .env

    #- name: 테스트 코드 실행
    #  run: npm run test

  CD:
    needs: CI
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        env:
          ENV: ${{ secrets.ENV }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: ENV
          script_stop: true
          script: |
            cd /home/ubuntu/test-project
            rm -rf .env
            git pull origin master
            echo "$ENV" > .env
            npm ci
            npm run build
            pm2 kill
            pm2 start dist/main.js --name "test"